#!/usr/bin/env bash

export PGUSER=${EXTRACTS_DB_USERNAME}
export PGPASSWORD=${EXTRACTS_DB_PASSWORD}
export PGDATABASE=${EXTRACTS_DB_NAME}
export PGHOST=${EXTRACTS_DB_HOST}

echo 'Using read-write credentials!'

psql

tail -f /dev/null
