#!/usr/bin/env bash

export PGUSER=${INFO_DB_USERNAME}
export PGPASSWORD=${INFO_DB_PASSWORD}
export PGDATABASE=${INFO_DB_NAME}
export PGHOST=${INFO_DB_HOST}

echo 'Using read-write credentials!'

psql

tail -f /dev/null
