#!/usr/bin/env bash

export PGUSER=${CASEWORK_DB_USERNAME}
export PGPASSWORD=${CASEWORK_DB_PASSWORD}
export PGDATABASE=${CASEWORK_DB_SCHEMA_NAME}
export PGHOST=${CASEWORK_DB_HOST}
export PGPORT=${CASEWORK_DB_PORT}

echo 'Using read-write credentials!'

psql

tail -f /dev/null
