apiVersion: apps/v1
kind: Deployment
metadata:
  name: hocs-toolbox
  labels:
    version: {{.VERSION}}
  annotations:
    downscaler/downscale-period: 'Mon-Fri 18:00-08:00 Europe/London'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hocs-toolbox
  template:
    metadata:
      labels:
        name: hocs-toolbox
        version: {{.VERSION}}
        role: hocs-backend
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: hocs-toolbox-query
          image: quay.io/ukhomeofficedigital/hocs-toolbox:{{.VERSION}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
               - SETUID
               - SETGID
          env:
            - name: MODE
              value: "query"
            - name: KUBE_NAMESPACE
              value: {{.KUBE_NAMESPACE}}
            - name: HOCS_DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-rds
                  key: endpoint
            - name: HOCS_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-rds
                  key: port
            - name: HOCS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-rds
                  key: db_name
            - name: HOCS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-rds
                  key: username
            - name: HOCS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-rds
                  key: password
            - name: HOCS_INFO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-rds
                  key: info_username
            - name: HOCS_INFO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-rds
                  key: info_password
            - name: HOCS_DOCS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hocs-docs
                  key: rds_user
            - name: HOCS_DOCS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hocs-docs
                  key: rds_password
            - name: HOCS_CASEWORK_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hocs-casework
                  key: rds_user
            - name: HOCS_CASEWORK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hocs-casework
                  key: rds_password
            - name: HOCS_WORKFLOW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hocs-workflow
                  key: rds_user
            - name: HOCS_WORKFLOW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hocs-workflow
                  key: rds_password
            - name: HOCS_AUDIT_DB_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-rds-audit
                  key: endpoint
            - name: HOCS_AUDIT_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-rds-audit
                  key: db_name
            - name: HOCS_AUDIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hocs-audit
                  key: rds_user
            - name: HOCS_AUDIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hocs-audit
                  key: rds_password
            - name: ELASTICSEARCH_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-elasticsearch
                  key: access_key_id
            - name: ELASTICSEARCH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-elasticsearch
                  key: secret_access_key
            - name: SEARCH_QUEUE_NAME
              value: {{.KUBE_NAMESPACE}}-search-sqs
            - name: SEARCH_QUEUE_DLQ_NAME
              value: {{.KUBE_NAMESPACE}}-search-sqs-dlq
            - name: AWS_SEARCH_SQS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-search-sqs
                  key: access_key_id
            - name: AWS_SEARCH_SQS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-search-sqs
                  key: secret_access_key
            - name: DOCUMENT_QUEUE_NAME
              value: {{.KUBE_NAMESPACE}}-document-sqs
            - name: DOCUMENT_QUEUE_DLQ_NAME
              value: {{.KUBE_NAMESPACE}}-document-sqs-dlq
            - name: AWS_DOCUMENT_SQS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-document-sqs
                  key: access_key_id
            - name: AWS_DOCUMENT_SQS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-document-sqs
                  key: secret_access_key
            - name: AUDIT_QUEUE_NAME
              value: {{.KUBE_NAMESPACE}}-audit-sqs
            - name: AUDIT_QUEUE_DLQ_NAME
              value: {{.KUBE_NAMESPACE}}-audit-sqs-dlq
            - name: AWS_AUDIT_SQS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-audit-sqs
                  key: access_key_id
            - name: AWS_AUDIT_SQS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-audit-sqs
                  key: secret_access_key
            - name: S3_REGION
              value: 'eu-west-2'
            - name: S3_UNTRUSTED_BUCKET
              value: {{.KUBE_NAMESPACE}}-untrusted-s3
            - name: S3_UNTRUSTED_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-untrusted-s3
                  key: access_key_id
            - name: S3_UNTRUSTED_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-untrusted-s3
                  key: secret_access_key
            - name: S3_UNTRUSTED_KMS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-untrusted-s3
                  key: kms_key_id
            - name: S3_TRUSTED_BUCKET
              value: {{.KUBE_NAMESPACE}}-trusted-s3
            - name: S3_TRUSTED_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-trusted-s3
                  key: access_key_id
            - name: S3_TRUSTED_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-trusted-s3
                  key: secret_access_key
            - name: S3_TRUSTED_KMS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-trusted-s3
                  key: kms_key_id
            - name: AWS_ACCOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: hocs-queue-config
                  key: AWS_ACCOUNT_ID
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
