apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cms-data-backup-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-encrypted
  resources:
    requests:
      storage: 350Gi
