pipeline:

  docker-build:
      image: docker:17.09.1
      environment:
        - DOCKER_HOST=tcp://172.17.0.1:2375
      commands:
        - docker build -t hocs-toolbox .
      when:
        branch: [master, refs/tags/*]
        event: [push, tag]

  install-docker-image:
      image: docker:17.09.1
      environment:
        - DOCKER_HOST=tcp://172.17.0.1:2375
      secrets:
        - docker_password
      commands:
        - docker login -u=hocs-bot -p=$${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
        - docker tag hocs-toolbox docker.digital.homeoffice.gov.uk/hocs-toolbox:build-$${DRONE_BUILD_NUMBER}
        - docker tag hocs-toolbox docker.digital.homeoffice.gov.uk/hocs-toolbox:latest
        - docker push docker.digital.homeoffice.gov.uk/hocs-toolbox:build-$${DRONE_BUILD_NUMBER}
        - docker push docker.digital.homeoffice.gov.uk/hocs-toolbox:latest
      when:
        branch: master
        event: push

  deploy-to-cs-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - KUBE_NAMESPACE=cs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_postgres_dev
    commands:
      - cd kube
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deploy-to-wcs-dev-from-build-number:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - KUBE_NAMESPACE=wcs-dev
      - ENVIRONMENT=dev
      - VERSION=build-${DRONE_BUILD_NUMBER}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_postgres_dev
    commands:
      - cd kube
      - ./deploy.sh
    when:
      branch: master
      event: [push, tag]

  deployment:
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    environment:
      - ENVIRONMENT=${DRONE_DEPLOY_TO}
      - KUBE_SERVER=https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    secrets:
      - hocs_postgres_dev
      - hocs_postgres_qa
      - hocs_postgres_demo
    commands:
      - cd kube
      - ./deploy.sh
    when:
      event: deployment
      environment: [dev, qa, demo]

  deploy-to-prod:
      image: quay.io/ukhomeofficedigital/kd:v1.16.0
      environment:
        - ENVIRONMENT=prod
        - VERSION=${IMAGE_VERSION}
        - KUBE_SERVER=https://kube-api-prod.prod.acp.homeoffice.gov.uk
      secrets:
        - hocs_postgres_prod
      commands:
        - cd kube
        - ./deploy.sh
      when:
        event: deployment
        environment: prod
