---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push

steps:
  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-toolbox
      tags:
        - build_${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_SHA}
        - branch-${DRONE_COMMIT_BRANCH/\//_}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot

---

# we're doing this as a promote to test the script
# in reality this should normally be defined in hocs-data's .drone.yml

kind: pipeline
type: kubernetes
name: teardown-gamma

trigger:
  event:
    - promote
  target:
    - teardown

steps:
  - name: teardown gamma
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - bash ./teardown.sh
    environment:
      ENVIRONMENT: hocs-gamma
      KUBE_TOKEN:
        from_secret: hocs_toolbox_hocs_gamma
...
