---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: docker-build
    pull: if-not-exists
    image: docker:17.09.1
    commands:
      - docker build -t hocs-toolbox .
    environment:
      DOCKER_HOST: tcp://172.17.0.1:2375
    when:
      branch:
        - master
        - refs/tags/*
      event:
        - push
        - tag

  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-toolbox
      tags:
        - build_${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_SHA}
        - branch-${DRONE_COMMIT_BRANCH/\//_}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot

  - name: deploy-to-cs-dev-from-build-number
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: dev
      HOCS_POSTGRES_DEV:
        from_secret: hocs_postgres_dev
      KUBE_NAMESPACE: cs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      VERSION: build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        - main
      event:
        - push
        - tag

  - name: deploy-to-wcs-dev-from-build-number
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: dev
      HOCS_POSTGRES_DEV:
        from_secret: hocs_postgres_dev
      KUBE_NAMESPACE: wcs-dev
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
      VERSION: build-${DRONE_BUILD_NUMBER}
    when:
      branch:
        - master
      event:
        - push
        - tag

  - name: deployment
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      HOCS_POSTGRES_DEMO:
        from_secret: hocs_postgres_demo
      HOCS_POSTGRES_DEV:
        from_secret: hocs_postgres_dev
      HOCS_POSTGRES_QA:
        from_secret: hocs_postgres_qa
      KUBE_SERVER: https://kube-api-notprod.notprod.acp.homeoffice.gov.uk
    when:
      event:
        - deployment
      target:
        - dev
        - qa
        - demo

  - name: deploy-to-prod
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - ./deploy.sh
    environment:
      ENVIRONMENT: prod
      HOCS_POSTGRES_PROD:
        from_secret: hocs_postgres_prod
      KUBE_SERVER: https://kube-api-prod.prod.acp.homeoffice.gov.uk
      VERSION: ${IMAGE_VERSION}
    when:
      event:
        - deployment
      target:
        - prod

...
