---
kind: pipeline
type: kubernetes
name: build
trigger:
  event:
    - push
  branch:
    exclude:
      - main

steps:
  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-toolbox
      tags:
        - ${DRONE_COMMIT_SHA}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - clone

---
kind: pipeline
type: kubernetes
name: build tag
trigger:
  event:
    - tag
  branch:
    - main

steps:

  - name: build & push tag main
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-toolbox
      tags:
        - ${DRONE_TAG}
        - ${DRONE_COMMIT_SHA}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - test project

---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main
depends_on:
  - build tag

steps:
  - &deploy
      name: cs-dev
      image: quay.io/ukhomeofficedigital/kd
      environment:
        VERSION: ${DRONE_TAG}
        KUBE_TOKEN:
          from_secret: hocs_toolbox
      commands:
        - cd kube
        - ./deploy.sh
      depends_on:
        - clone

  - <<: *deploy
    name: cs-qa
  - <<: *deploy
    name: cs-demo
  - <<: *deploy
    name: wcs-dev
  - <<: *deploy
    name: wcs-qa
  - <<: *deploy
    name: wcs-demo
  - <<: *deploy
    name: hocs-delta
  - <<: *deploy
    name: hocs-gamma
  - <<: *deploy
    name: hocs-epsilon
  - <<: *deploy
    name: hocs-qax
  - <<: *deploy
    name: cs-prod
  - <<: *deploy
    name: wcs-prod
