---
kind: pipeline
type: kubernetes
name: lint

trigger:
  event:
    - push

steps:
- name: lint bash
  image: koalaman/shellcheck-alpine
  commands:
    - shellcheck *.sh */*.sh */*/*.sh
  depends_on:
    - clone

---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: build & push safe
    image: plugins/docker
    depends_on:
      - clone
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-toolbox
      tags:
        - build_${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_SHA}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot

---

kind: pipeline
type: kubernetes
name: deploy
depends_on:
  - build

trigger:
  branch:
    - main
  event:
    - push

steps:
  - &deploySafe
      name: cs-demo
      image: quay.io/ukhomeofficedigital/kd
      environment:
        VERSION: ${DRONE_COMMIT_SHA}
        KUBE_TOKEN:
          from_secret: KUBE_TOKEN_SAFE
      commands:
        - cd kube
        - ./deploy.sh
      depends_on:
        - clone

  - <<: *deploySafe
    name: cs-dev
  - <<: *deploySafe
    name: cs-qa
 # - <<: *deploySafe # in definition ^
 #   name: cs-demo
  - <<: *deploySafe
    name: wcs-dev
  - <<: *deploySafe
    name: wcs-qa
  - <<: *deploySafe
    name: wcs-demo
  - <<: *deploySafe
    name: hocs-delta
  - <<: *deploySafe
    name: hocs-gamma
  - <<: *deploySafe
    name: hocs-epsilon
  - <<: *deploySafe
    name: hocs-qax

...
