---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - &deploy
    name: cs-prod
    image: quay.io/ukhomeofficedigital/kd
    environment:
      VERSION: ${DRONE_TAG}
      KUBE_TOKEN:
        from_secret: decs_prod_token
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - fetch and checkout
    when:
      target:
        include:
          - "*-prod"

  - <<: *deploy
    name: wcs-prod


---
kind: pipeline
type: kubernetes
name: deploy tag
trigger:
  event:
    - tag
  branch:
    - main

steps:
  - &deploy
      name: cs-dev
      image: quay.io/ukhomeofficedigital/kd
      environment:
        VERSION: ${DRONE_TAG}
        KUBE_TOKEN:
          from_secret: decs_notprod_token
      commands:
        - cd kube
        - ./deploy.sh
      depends_on:
        - clone

  - <<: *deploy
    name: cs-qa
  - <<: *deploy
    name: cs-demo
  - <<: *deploy
    name: wcs-dev
  - <<: *deploy
    name: wcs-qa
  - <<: *deploy
    name: wcs-demo
  - <<: *deploy
    name: hocs-qax
