---
kind: pipeline
type: kubernetes
name: build
trigger:
  event:
    - push
  branch:
    - cms-data-migration

steps:
  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-toolbox
      tags:
        - ${DRONE_COMMIT_SHA}-cms-migration
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - clone

---
kind: pipeline
type: kubernetes
name: deploy
trigger:
  event:
    - promote

steps:
  - name: fetch and checkout
    image: alpine/git
    commands:
      - git fetch --tags
      - git checkout $${VERSION}

  - &deploy
    name: cs-prod-migration
    image: quay.io/ukhomeofficedigital/kd
    environment:
      VERSION: ${DRONE_TAG}
      KUBE_TOKEN:
        from_secret: decs_prod_token
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - fetch and checkout
    when:
      target:
        include:
          - "*-prod-*"

---
kind: pipeline
type: kubernetes
name: build tag
trigger:
  event:
    - push
  branch:
    - cms-data-migration

steps:
  - name: cs-dev-migration
    image: quay.io/ukhomeofficedigital/kd
    environment:
      VERSION: ${DRONE_COMMIT_SHA}-cms-migration
      KUBE_TOKEN:
        from_secret: KUBE_TOKEN_SAFE
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - clone

...
