---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push

steps:
  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-toolbox
      tags:
        - build_${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_SHA}
        - branch-${DRONE_COMMIT_BRANCH/\//_}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - clone

  - name: build & push latest
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-toolbox
      tags:
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    when:
      branch:
        - main
    depends_on:
      - clone

---
# we're doing this as a promote so one can manually run it
# normally this is defined in hocs-data's .drone.yml

kind: pipeline
type: kubernetes
name: teardown

trigger:
  event:
    - promote

steps:
  - name: teardown non-mainline
    image: quay.io/ukhomeofficedigital/kd:v1.16.0
    commands:
      - cd kube
      - bash ./teardown.sh
    environment:
      ENVIRONMENT: ${DRONE_DEPLOY_TO}
      KUBE_TOKEN:
        from_secret: hocs_toolbox_${DRONE_DEPLOY_TO/-/_}
    when:
      target:
        - "hocs-*"
