---
kind: pipeline
type: kubernetes
name: lint

trigger:
  event:
    - push

steps:
- name: lint bash
  image: koalaman/shellcheck-alpine
  commands:
    - shellcheck *.sh */*.sh */*/*.sh
  depends_on:
    - clone

---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - cms-data-migration
  event:
    - push

steps:
  - name: build & push
    image: plugins/docker
    depends_on:
      - clone
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-toolbox
      tags:
        - ${DRONE_COMMIT_SHA}-cms-migration
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
      
---
kind: pipeline
type: kubernetes
name: deploy
depends_on:
  - build

trigger:
  branch:
    - cms-data-migration
  event:
    - push

steps:
  - name: cs-dev-migration
    image: quay.io/ukhomeofficedigital/kd
    environment:
      VERSION: ${DRONE_COMMIT_SHA}-cms-migration
      KUBE_TOKEN:
        from_secret: KUBE_TOKEN_SAFE
    commands:
      - cd kube
      - ./deploy.sh
    depends_on:
      - clone
...
