#!/usr/bin/env bash

export PGPASSWORD=${HOCS_AUDIT_PASSWORD}
export PGUSER=${HOCS_AUDIT_USERNAME}
export PGDATABASE=${HOCS_AUDIT_DB_NAME}
export PGHOST=${HOCS_AUDIT_DB_HOSTNAME}

psql

tail -f /dev/null
