#!/usr/bin/env bash

export PGUSER=${CASEWORK_DB_RO_USERNAME}
export PGPASSWORD=${CASEWORK_DB_RO_PASSWORD}
export PGDATABASE=${CASEWORK_DB_NAME}
export PGHOST=${CASEWORK_DB_HOST}

psql

tail -f /dev/null
