---
kind: pipeline
type: kubernetes
name: lint

trigger:
  event:
    - push

steps:
- name: lint bash
  image: koalaman/shellcheck-alpine
  commands:
    - shellcheck */*.sh
  depends_on:
    - clone
