name: 'Docker Build Tag'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    uses: UKHomeOffice/hocs-github-actions/.github/workflows/docker-build-tag.yml@v2
    with:
      images: 'quay.io/ukhomeofficedigital/hocs-toolbox'
    secrets: inherit
