name: 'SemVer Tag and Docker Build'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/semver-tag-docker.yml@v1
    with:
      image: 'quay.io/ukhomeofficedigital/hocs-toolbox'
    secrets: inherit
